version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    command: npm run start:dev